var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");

var gapi=window.gapi=window.gapi||{};gapi._bs=new Date().getTime();(function(){var f=null,g=window,h="push",i="replace",k="length";var m=g,r=document,v=m.location,w=function(){},z=/\[native code\]/,B=function(a,b,c){return a[b]=a[b]||c},C=function(a){for(var b=0;b<this[k];b++)if(this[b]===a)return b;return-1},D=function(){var a;if((a=Object.create)&&z.test(a))a=a(f);else{a={};for(var b in a)a[b]=void 0}return a},E=B(m,"gapi",{});var F;F=B(m,"___jsl",D());B(F,"I",0);B(F,"hel",10);var G=function(){var a=v.href,b;if(F.dpo)b=F.h;else{b=F.h;var c=RegExp("([#].*&|[#])jsh=([^&#]*)","g"),e=RegExp("([?#].*&|[?#])jsh=([^&#]*)","g");if(a=a&&(c.exec(a)||e.exec(a)))try{b=decodeURIComponent(a[2])}catch(d){}}return b},I=function(a){return B(B(F,"H",D()),a,D())};var J=B(F,"perf",D()),L=B(J,"g",D()),M=B(J,"i",D());B(J,"r",[]);D();D();var N=function(a,b,c){var e=J.r;"function"===typeof e?e(a,b,c):e[h]([a,b,c])},P=function(a,b,c){b&&0<b[k]&&(b=O(b),c&&0<c[k]&&(b+="___"+O(c)),28<b[k]&&(b=b.substr(0,28)+(b[k]-28)),c=b,b=B(M,"_p",D()),B(b,c,D())[a]=(new Date).getTime(),N(a,"_p",c))},O=function(a){return a.join("__")[i](/\./g,"_")[i](/\-/g,"_")[i](/\,/g,"_")};var Q=D(),R=[],S;S={a:"callback",g:"sync",e:"config",c:"_c",d:"h",l:"platform",i:"jsl",TIMEOUT:"timeout",f:"ontimeout",k:"mh",j:"u"};R[h]([S.i,function(a){for(var b in a)if(Object.prototype.hasOwnProperty.call(a,b)){var c=a[b];"object"==typeof c?F[b]=B(F,b,[]).concat(c):B(F,b,c)}if(b=a[S.j])a=B(F,"us",[]),a[h](b),(b=/^https:(.*)$/.exec(b))&&a[h]("http:"+b[1])}]);var T=decodeURI("%73cript");Q.m=function(a){var b=F.ms||"https://web.archive.org/web/20121026122604/https://apis.google.com";a=a[0];var c;if(!(c=!a))c=0<=a.indexOf("..");if(c)throw"Bad hint";return b+"/"+a[i](/^\//,"")};
var U=function(a){return a.join(",")[i](/\./g,"_")[i](/-/g,"_")},W=function(a,b){for(var c=[],e=0;e<a[k];++e){var d=a[e];d&&0>C.call(b,d)&&c[h](d)}return c},aa=/^[\/_a-zA-Z0-9,.\-!:=]+$/,ba=/^https?:\/\/[^\/\?#]+\.google\.com(:\d+)?\/[^\?#]+$/,ca=/\/cb=/g,da=/\/\//g,X=function(a){var b=r.createElement(T);b.setAttribute("src",a);b.async="true";a=r.getElementsByTagName(T)[0];a.parentNode.insertBefore(b,a)},Z=function(a,b){var c=b||{};"function"==typeof b&&(c={},c[S.a]=b);var e=c,d=e&&e[S.c];if(d)for(var j=
0;j<R[k];j++){var l=R[j][0],n=R[j][1];n&&Object.prototype.hasOwnProperty.call(d,l)&&n(d[l],a,e)}e=a?a.split(":"):[];if(!(d=c[S.d]))if(d=G(),!d)throw"Bad hint";j=d;l=B(F,"ah",D());if(!l["::"]||!e[k])Y(e||[],c,j);else{d=[];for(n=f;n=e.shift();){var q=n.split("."),q=l[n]||l[q[1]&&"ns:"+q[0]||""]||j,u=d[k]&&d[d[k]-1]||f,x=u;if(!u||u.hint!=q)x={hint:q,b:[]},d[h](x);x.b[h](n)}var A=d[k];if(1<A){var y=c[S.a];y&&(c[S.a]=function(){0==--A&&y()})}for(;e=d.shift();)Y(e.b,c,e.hint)}},Y=function(a,b,c){var e=
a.sort();a=[];for(var d=void 0,j=0;j<e[k];j++){var l=e[j];l!=d&&a[h](l);d=l}a=a||[];var n=b[S.a],q=b[S.e],d=b[S.TIMEOUT],u=b[S.f],x=f,A=!1;if(d&&!u||!d&&u)throw"Timeout requires both the timeout parameter and ontimeout parameter to be set";var e=B(I(c),"r",[]).sort(),y=B(I(c),"L",[]).sort(),H=[].concat(e),V=function(a,b){if(A)return 0;m.clearTimeout(x);y[h].apply(y,p);var d=((E||{}).config||{}).update;d?d(q):q&&B(F,"cu",[])[h](q);if(b){P("me0",a,H);try{$(function(){var a;a=c===G()?B(E,"_",D()):D();
a=B(I(c),"_",a);b(a)})}finally{P("me1",a,H)}}n&&n();return 1};0<d&&(x=m.setTimeout(function(){A=!0;u()},d));var p=W(a,y);if(p[k]){var p=W(a,e),s=B(F,"CP",[]),t=s[k];s[t]=function(a){if(!a)return 0;P("ml1",p,H);var b=function(){s[t]=f;return V(p,a)};if(0<t&&s[t-1])s[t]=b;else for(b();(b=s[++t])&&b(););};if(p[k]){var K="loaded_"+F.I++;E[K]=function(a){s[t](a);E[K]=f};a=c.split(";");a=(d=Q[a.shift()])&&d(a);if(!a)throw"Bad hint:"+c;d=a=a[i]("__features__",U(p))[i](/\/$/,"")+(e[k]?"/ed=1/exm="+U(e):"")+
("/cb=gapi."+K);j=d.match(da);l=d.match(ca);if(!l||!(1===l[k]&&ba.test(d)&&aa.test(d)&&j&&1===j[k]))throw"Bad URL "+a;e[h].apply(e,p);P("ml0",p,H);b[S.g]||m.___gapisync?(b=a,"loading"!=r.readyState?X(b):r.write("<"+T+' src="'+encodeURI(b)+'"></'+T+">")):X(a)}else s[t](w)}else V(p)};var $=function(a){if(F.hee&&0<F.hel)try{return a()}catch(b){F.hel--,Z("debug_error",function(){g.___jsl.hefn(b)})}else return a()};E.load=function(a,b){return $(function(){return Z(a,b)})};L.bs0=g.gapi._bs||(new Date).getTime();N("bs0");L.bs1=(new Date).getTime();N("bs1");delete g.gapi._bs;})();
gapi.load("plusone-unsupported",{callback:window["gapi_onload"],_c:{"jsl":{"ci":{"services":{},"lexps":[17,69,71,80,82,61,74,75,30,45],"inline":{"css":1},"report":{},"oauth-flow":{},"isPlusUser":false,"iframes":{"additnow":{"url":"https://web.archive.org/web/20121026122604/https://apis.google.com/additnow/additnow.html?bsv\u003dm\u0026abtk\u003dAEIZW7Qo6fP/jFptO1uGZTjmpNw%2BxZdJ0oTu6YizWDNcjZuixQCPZBC3BdP0f2IlcLpnS/RUBQvDlT/rgYrMF0ThiXQd8XUFwQTPrmq1edffNBeinUiwm6o%3D"},"plus":{"methods":["onauth","oninvitewidgetclick"],"url":":socialhost:/u/:session_index:/_/pages/badge?bsv\u003dm\u0026abtk\u003dAEIZW7Q4%2Bb7B%2Bj9S7jeao/8kkS77x0qMMoeHoi99i60dk01t1tVIHo2lkGITVKgmAqDj7gB7fGI4YG2pRjPXzPLA28iU9slEKfKSYaaVtjC2Y8jS9hlGBrA%3D"},":socialhost:":"https://web.archive.org/web/20121026122604/https://plusone.google.com","plus_circle":{"params":{"url":""},"url":":socialhost:/:session_prefix:_/widget/plus/circle?bsv\u003dm\u0026abtk\u003dAEIZW7RX0Z%2Bh99HcFem%2BIL38HFHlPwpcdGHpF2TsS3/3Xhoznluil3RkVrdsQ0D4WUGeRYvjSG1mDZiUvE5z2jOUBVLQRq3U5juL6kKevfaj%2B8b1DDW5yzQ%3D"},"evwidget":{"params":{"url":""},"url":":socialhost:/:session_prefix:_/events/widget?bsv\u003dm\u0026abtk\u003dAEIZW7Sd5ZuCLiE3niS3QriAZxwB35tVNctFw0TdMeuNPb6olnMvDerVkmprp8sTHS5Tz9avZoeEqek15SgvME1sDgBCBJKSOkRNTNav1tJT07V/cWKhGVI%3D"},":signuphost:":"https://web.archive.org/web/20121026122604/https://plus.google.com","plusone":{"preloadUrl":["https://web.archive.org/web/20121026122604/https://ssl.gstatic.com/s2/oz/images/stars/po/Publisher/sprite4-a67f741843ffc4220554c34bd01bb0bb.png"],"params":{"count":"","size":"","url":""},"url":":socialhost:/:session_prefix:_/+1/fastbutton?bsv\u003dm\u0026abtk\u003dAEIZW7TEBxdk2OxKnpQfDqKDqnydRis%2B1uAjjK37nNaezK7XVONc6FvLv8c9nkkBjgXZLQigQSOyg0dye2JfLFB71RwCNbByiFl4FDqn7Q0El2YdciVf1Hk%3D"},"plus_share":{"params":{"url":""},"url":":socialhost:/:session_prefix:_/+1/sharebutton?plusShare\u003dtrue\u0026bsv\u003dm\u0026abtk\u003dAEIZW7T6b%2BXZjywh2sOpuLXvbQ45Lp99L/DQXLDd4HoJhlmyUbqex3Qb0Vb4Im4IxBiW5ZHLU5rZLsJZ6dROY70OQRd%2BhQnGQ3XdqorfPYSF6G3mpcwsxHc%3D"}},"debug":{"host":"https://web.archive.org/web/20121026122604/https://plusone.google.com","reportExceptionRate":0.05,"rethrowException":true},"csi":{"rate":0.0},"googleapis.config":{"mobilesignupurl":"https://web.archive.org/web/20121026122604/https://m.google.com/app/plus/oob?"}},"h":"m;/_/apps-static/_/js/gapi/__features__/rt\u003dj/ver\u003dRiMmm1NrQTI.en_US./sv\u003d1/am\u003d!6rz0p3va2LWId_D6JA/d\u003d1/rs\u003dAItRSTMzcCTyovtZzsK3qzTpJP2YGN7JXw","u":"https://web.archive.org/web/20121026122604/https://apis.google.com/js/plusone.js","hee":true,"fp":"30351551fefb5852e3cc0f39ca59dce5fe86a9a0","dpo":false},"fp":"30351551fefb5852e3cc0f39ca59dce5fe86a9a0","annotation":[]}});

}
/*
     FILE ARCHIVED ON 12:26:04 Oct 26, 2012 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 03:43:52 Sep 07, 2025.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  captures_list: 0.603
  exclusion.robots: 0.032
  exclusion.robots.policy: 0.023
  esindex: 0.011
  cdx.remote: 23.749
  LoadShardBlock: 293.614 (6)
  PetaboxLoader3.datanode: 272.394 (7)
  load_resource: 187.235
  PetaboxLoader3.resolve: 82.623
*/